# Parts borrowed from create-t3-app <3 https://github.com/t3-oss/create-t3-app/blob/next/.github/workflows/ci.yml

# this workflow will run on every pr to make sure the project is following the guidelines

name: CI

on:
  pull_request:
    branches: ["*"]

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest
    name: Validate PR Title
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
